name       : haskell-errors
version    : 2.1.3
release    : 1
source     :
    - http://hackage.haskell.org/package/errors-2.1.3/errors-2.1.3.tar.gz : 201a1d9d2fba16dff734eb79e07f138718ed62f5a0a846cf0cee743828844df1
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library encourages an error-handling style that directly uses the type system, rather than out-of-band exceptions.
description: |
    This library encourages an error-handling style that directly uses the type system, rather than out-of-band exceptions.
builddeps  :
    - haskell-cabal-install
    - haskell-safe
    - haskell-transformers-compat
    - haskell-unexceptionalio
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register