name       : haskell-errors
version    : 2.3.0
release    : 2
source     :
    - https://hackage.haskell.org/package/errors-2.3.0/errors-2.3.0.tar.gz : 6772e5689f07e82077ffe3339bc672934d83d83a97a7d4f1349de1302cb71f75
license    : BSD-3-Clause
component  : programming.haskell
summary    : This library encourages an error-handling style that directly uses the type system, rather than out-of-band exceptions.
description: |
    This library encourages an error-handling style that directly uses the type system, rather than out-of-band exceptions.
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-safe-devel
    - haskell-transformers-compat-devel
    - haskell-unexceptionalio-devel
rundeps    :
    - devel:
        - haskell-exceptions-devel
        - haskell-safe-devel
        - haskell-transformers-compat-devel
        - haskell-unexceptionalio-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
